### PR TITLE
Add Blazegraph to docker

### PR DESCRIPTION
**Pull request by aaron-collier**
Adds blazegraph to the docker stack and sets the environment variable for the api executable.

### CODE REVIEW

**Comment by jcoyne** [comment]
Instead of adding a huge binary to the repo, couldn't we just `docker run lyrasis/blazegraph:2.1.4` ?

**Comment by aaron-collier** [comment]
@jcoyne good call, I'll update.

**Comment by aaron-collier** [comment]
May have spoke too soon. The image doesn't properly (as of yet) actually run the server. This old issue (https://stackoverflow.com/questions/33368741/docker-container-with-blazegraph-triple-store-not-working-possibly-due-to-networ) is what I'm seeing. Trying a few things, but we may have to use the other route and try to avoid storing the binary or something.

**Comment by aaron-collier** [comment]
Ok, that took a bit... the path changes from /blazegraph to /bigdata when using the image.

**Pull request merged**
